// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orxbevutabalpgaidgfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeGJldnV0YWJhbHBnYWlkZ2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzI3ODksImV4cCI6MjA2MzI0ODc4OX0.Mm9-kEd0lQ38UjT9OXGt5Bso0-0JVMVNwjtlDn0FB0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);