// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxrdkbbnlofxljdxhpnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cmRrYmJubG9meGxqZHhocG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODY0NzcsImV4cCI6MjA2NTA2MjQ3N30.Gwxark9H_H4U2we5iFO-CrEq-s8Q91gn_b781Gy8se8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);